[tool.poetry]
name = "naturalql"
version = "0.1.0"
description = "Natural language to guardrailed SQL (Streamlit + DuckDB)"
authors = ["Paolo Notaro <paolo.notaro@outlook.com>"]
readme = "README.md"
packages = [{ include = "naturalql", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
streamlit = "1.38.0"
pandas = "2.2.2"
sqlglot = "25.9.0"
openai = ">=1.40.0"
python-dotenv = "1.0.1"
duckdb = "0.10.3"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"